##===- tools/acse-cc/Makefile ------------------------------*- Makefile -*-===##

LEVEL = ../..

TOOLNAME = acse-cc

LINK_COMPONENTS = support
USEDLIBS = acseCompile.a acseParse.a acseLex.a

include $(LEVEL)/Makefile.common
