##===- tools/acse-parse/Makfile ----------------------------*- Makefile -*-===##

LEVEL = ../..

TOOLNAME = acse-parse

LINK_COMPONENTS = support
USEDLIBS = acseParse.a acseLex.a

include $(LEVEL)/Makefile.common
