##===- tools/Makefile --------------------------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL = ..

#
# List all of the subdirectories that we will compile.
#
DIRS = acse-lex acse-parse acse-cc

include $(LEVEL)/Makefile.common
